steps:
  - name: node
    entrypoint: npm
    args: ['-v']

  - name: node
    entrypoint: /bin/bash
    args:
    - -c
    - | 
      cd web/modules/home && npm install && npm build
      cd ../../..
      npm install

  - name: gcr.io/fastro-319406/firebase
    args: ['deploy', '--project=fastro-319406', '--only=hosting']