steps:
  - name: node:lts
    entrypoint: /bin/bash
    args:
    - -c
    - | 
      npm install -verbose -w @fastro/home
      npm run build -w @fastro/home
      npm install

  - name: gcr.io/fastro-319406/firebase
    args: ['deploy', '--project=fastro-319406']